name: Nuki Cleaner

on:
  schedule:
    # Run every 1 hour (at minute 0 of hours 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23)
    - cron: '0 */1 * * *'
  workflow_dispatch: # Allow manual triggering

jobs:
  clean-nuki-auth:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Enable Corepack
        run: corepack enable

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --immutable

      - name: Run Nuki cleaner
        run: yarn start
        env:
          NUKI_WEB_TOKEN: ${{ secrets.NUKI_WEB_TOKEN }}
          SMARTLOCK_ID: ${{ secrets.SMARTLOCK_ID }}
